### PR TITLE
retro-user.bbclass: fix useradd for master branch

### PR DESCRIPTION
**Pull request by MarkusVolk**

### CODE REVIEW

**Comment by dev-0x7C6** [comment]
@MarkusVolk Is this change backward compatible? Maybe we should use long parameter (`--password`) if not?

**Comment by MarkusVolk** [comment]
According to useradd manpage it has to be `-p` or `--password`. `-P` isn't mentioned there. So i guess it will be backwards compatible. 
Maybe --password would look a little nicer?

with `-P` i get this on master branch:
```
The stack trace of python calls that resulted in this exception/failure was:
File: 'exec_python_func() autogenerated', lineno: 2, function: <module>
     0001:
 *** 0002:useradd_sysroot_sstate(d)
     0003:
File: '/home/flk/build/poky/meta/classes/useradd.bbclass', lineno: 152, function: useradd_sysroot_sstate
     0148:        bb.build.exec_func("useradd_sysroot", d)
     0149:    elif task == "prepare_recipe_sysroot":
     0150:        # Used to update this recipe's own sysroot so the user/groups are available to do_install
     0151:        scriptfile = d.expand("${RECIPE_SYSROOT}${bindir}/postinst-useradd-${PN}")
 *** 0152:        bb.build.exec_func("useradd_sysroot", d)
     0153:    elif task == "populate_sysroot":
     0154:        # Used when installed in dependent task sysroots
     0155:        scriptfile = d.expand("${SYSROOT_DESTDIR}${bindir}/postinst-useradd-${PN}")
     0156:
File: '/home/flk/build/poky/bitbake/lib/bb/build.py', lineno: 256, function: exec_func
     0252:    with bb.utils.fileslocked(lockfiles):
     0253:        if ispython:
     0254:            exec_func_python(func, d, runfile, cwd=adir)
     0255:        else:
 *** 0256:            exec_func_shell(func, d, runfile, cwd=adir)
     0257:
     0258:    try:
     0259:        curcwd = os.getcwd()
     0260:    except:
File: '/home/flk/build/poky/bitbake/lib/bb/build.py', lineno: 503, function: exec_func_shell
     0499:    with open(fifopath, 'r+b', buffering=0) as fifo:
     0500:        try:
     0501:            bb.debug(2, "Executing shell function %s" % func)
     0502:            with open(os.devnull, 'r+') as stdin, logfile:
 *** 0503:                bb.process.run(cmd, shell=False, stdin=stdin, log=logfile, extrafiles=[(fifo,readfifo)])
     0504:        except bb.process.ExecutionError as exe:
     0505:            # Find the backtrace that the shell trap generated
     0506:            backtrace_marker_regex = re.compile(r"WARNING: Backtrace \(BB generated script\)")
     0507:            stdout_lines = (exe.stdout or "").split("\n")
File: '/home/flk/build/poky/bitbake/lib/bb/process.py', lineno: 184, function: run
     0180:        if not stderr is None:
     0181:            stderr = stderr.decode("utf-8")
     0182:
     0183:    if pipe.returncode != 0:
 *** 0184:        raise ExecutionError(cmd, pipe.returncode, stdout, stderr)
     0185:    return stdout, stderr
Exception: bb.process.ExecutionError: Execution of '/home/flk/build/poky/build-rock/tmp/work/cortexa72-cortexa53-crypto-poky-linux/system-config/1.0-r0/temp/run.useradd_sysroot.168386' failed with exit code 1:
```

**Comment by MarkusVolk** [comment]
@dev-0x7C6 Changed it to --password. This also works for me and it looks nicer and better readable

**Comment by MarkusVolk** [comment]
@dev-0x7C6 This doesn't fix the problem. It seems like only -P is allowed in the open-embedded useradd Implementation. Changing it to -p or --password does only workaround this issue and seems to be ignored. The build doesn't break but the final image has no password set.

**Comment by dev-0x7C6** [comment]
@MarkusVolk maybe we should wait and see. Are you on poky/master? (maybe it is good idea to settle with 3.4_M2 tag). I'm still on hardknott branch, this might create little out-of-sync experience for master branch. I think I'll switch shortly.

p.s. override syntax is backported into hardknott, gatesgarth and dunfell.

**Comment by MarkusVolk** [comment]
@dev-0x7C6  yes, i switched to poky master. Originally i had panned to wait until 3.4_m3 was released but i had some spare time and therefore i jumped in at the deep end. There are still some major changes pending like switch to glibc 2.34 but good news is, that the master branch runs quite well on rockchip. I guess there is quite some work left to align the rpi patches.

Also checked the mailing list and didn't find any related problems. Maybe its just a local misconfiguration. Time will tell. For now i have an acceptable workaround for this:
I removed the -P line from retro-user.class and do password generation manually  like this:
https://github.com/MarkusVolk/meta-retro-wayland/blob/5c0ae170b22e4a194e7b8ea91dafd932b1e2f6a4/recipes-core/images/retro-image-standard.bbappend#L1

About backward compatibility i read, that there is an additional patch needed to support the new syntax in older yocto branches and for now this is only included in dunfell.

**Comment by dev-0x7C6** [comment]
@MarkusVolk 325a2af you may want to set `RETRO_USERADD_SET_PASSWORD` empty as workaround for the time being. Maybe this regression is related to recent override syntax change.

**Comment by dev-0x7C6** [comment]
2be0a7a allow customize almost every aspect of retro-user

**Pull request closed without merging**
